spring:
  profiles: server2
server:
  port: 8762
eureka:
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉取信息，如果开启，可能会有报错，不影响。原因是service初始化未完成，节点还没生成，客户端拉取信息执行了。
    fetchRegistry: true
    # eureka server地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    # 在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
    waitTimeInMsWhenSyncEmpty: 60000
    # 自我保护模式，当出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    enableSelfPreservation: true
    # 集群里eureka节点的变化信息更新的时间间隔，单位为毫秒，默认为10 * 60 * 1000
    peerEurekaNodesUpdateIntervalMs: 600000




