spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1091478765/springCloud-config
          username: 1091478765
          password: ll1993223
          #远程配置文件拉取到本地的文件路径
          #basedir: "C:\Users\VULCAN\Desktop"
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 8095


