spring:
  profiles:
    active: dev
  application:
      name: homefax-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: homefax-config
zuul:
  routes:
    sensitiveHeaders:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always